# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ihs06/cnn_svm_hybrid/Vivado/Final/Final.srcs/sources_1/ip/instr_bram/instr_bram.xci
# IP: The module: 'instr_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ihs06/cnn_svm_hybrid/Vivado/Final/Final.gen/sources_1/ip/instr_bram/instr_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ihs06/cnn_svm_hybrid/Vivado/Final/Final.srcs/sources_1/ip/instr_bram/instr_bram.xci
# IP: The module: 'instr_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ihs06/cnn_svm_hybrid/Vivado/Final/Final.gen/sources_1/ip/instr_bram/instr_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
